# Generated by Django 5.1.5 on 2025-05-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.classe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='note',
            field=models.ManyToManyField(through='mainApp.Note', to='mainApp.matiere'),
        ),
    ]
