# Generated by Django 5.1.5 on 2025-05-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='classe',
            new_name='classeEtudiant',
        ),
    ]
