# Generated by Django 5.1.5 on 2025-05-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_classe_etudiant_classeetudiant'),
        ('mainApp', '0002_absence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='Date',
            new_name='dateAbssence',
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEnseignement', models.DateTimeField()),
                ('classeEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignement', to='UserApp.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.matiere')),
            ],
        ),
    ]
