# Generated by Django 5.1.5 on 2025-05-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_date_absence_dateabssence_enseignement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignement',
            name='dateEnseignement',
        ),
        migrations.AddField(
            model_name='enseignement',
            name='heure',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='jour',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], default=None, max_length=10),
        ),
    ]
