# Generated by Django 5.1.5 on 2025-05-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_enseignement_dateenseignement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='heure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='jour',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10),
        ),
    ]
