# Generated by Django 5.1.5 on 2025-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_enseignement_heure_alter_enseignement_jour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignement',
            old_name='heure',
            new_name='heureDepart',
        ),
        migrations.RemoveField(
            model_name='note',
            name='typeDevoir',
        ),
        migrations.AddField(
            model_name='note',
            name='ds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='examen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
