# Generated by Django 5.1.5 on 2025-05-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_heure_enseignement_heuredepart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='valeur',
        ),
    ]
